package library;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ashutosh
 */
public class AdminMenu extends javax.swing.JFrame {

        /**
         * Creates new form AdminMenu
         */
        public AdminMenu() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton2 = new javax.swing.JButton();
                jButton8 = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();
                jButton6 = new javax.swing.JButton();
                jButton7 = new javax.swing.JButton();
                jButton9 = new javax.swing.JButton();
                jButton10 = new javax.swing.JButton();
                jButton11 = new javax.swing.JButton();

                FormListener formListener = new FormListener();

                jButton2.setText("jButton2");

                jButton8.setText("jButton8");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jButton1.setText("Add Teacher");
                jButton1.addActionListener(formListener);

                jButton3.setText("Add Books");
                jButton3.addActionListener(formListener);

                jButton4.setText("Add Student");
                jButton4.addActionListener(formListener);

                jButton5.setText("Reset Database");
                jButton5.addActionListener(formListener);

                jButton6.setText("View All students");
                jButton6.addActionListener(formListener);

                jButton7.setText("View All Teachers");
                jButton7.addActionListener(formListener);

                jButton9.setText("Search Issued Books");
                jButton9.addActionListener(formListener);

                jButton10.setText("Search All Books");
                jButton10.addActionListener(formListener);

                jButton11.setText("Logout");
                jButton11.addActionListener(formListener);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(43, 43, 43)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(47, 47, 47)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(135, 135, 135)
                                                .addComponent(jButton9)
                                                .addGap(49, 49, 49)
                                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(294, 294, 294)
                                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(116, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                );

                pack();
        }

        // Code for dispatching events from components to event handlers.

        private class FormListener implements java.awt.event.ActionListener {
                FormListener() {}
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                        if (evt.getSource() == jButton1) {
                                AdminMenu.this.jButton1ActionPerformed(evt);
                        }
                        else if (evt.getSource() == jButton5) {
                                AdminMenu.this.jButton5ActionPerformed(evt);
                        }
                        else if (evt.getSource() == jButton9) {
                                AdminMenu.this.jButton9ActionPerformed(evt);
                        }
                        else if (evt.getSource() == jButton10) {
                                AdminMenu.this.jButton10ActionPerformed(evt);
                        }
                        else if (evt.getSource() == jButton11) {
                                AdminMenu.this.jButton11ActionPerformed(evt);
                        }
                        else if (evt.getSource() == jButton4) {
                                AdminMenu.this.jButton4ActionPerformed(evt);
                        }
                        else if (evt.getSource() == jButton6) {
                                AdminMenu.this.jButton6ActionPerformed(evt);
                        }
                        else if (evt.getSource() == jButton7) {
                                AdminMenu.this.jButton7ActionPerformed(evt);
                        }
                        else if (evt.getSource() == jButton3) {
                                AdminMenu.this.jButton3ActionPerformed(evt);
                        }
                }
        }// </editor-fold>//GEN-END:initComponents

        private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
                // TODO add your handling code here:
                JFrame f = new JFrame("Book List"); 
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                Connection con = Library.connect();
                String sql="SELECT BOOK.BOOK_NAME, BOOK.BOOK_ID, BOOK.BOOK_NAME, BOOK.BOOK_AUTHOR, BOOK.BOOK_PUBLISHER, BOOK.BOOK_SHELF, ISSUEDBOOKS.STUDENT_ID FROM BOOK INNER JOIN ISSUEDBOOKS ON BOOK.BOOK_ID = ISSUEDBOOKS.BOOK_ID";
                try {
                        Statement stmt = con.createStatement();
                        stmt.executeUpdate("USE LIBRARYMANAGEMENTSYSTEM");
                        ResultSet rs = stmt.executeQuery(sql);
                        JTable book_list= new JTable(Library.buildTableModel(rs)); 
                        JScrollPane scrollPane = new JScrollPane(book_list); 
                        f.add(scrollPane);
                        f.setSize(800, 400); 
                        f.setVisible(true);
                        f.setLocationRelativeTo(null);
                } catch (Exception e) {
                     e.printStackTrace();
                }  
        }//GEN-LAST:event_jButton9ActionPerformed

        private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                // TODO add your handling code here:
                JFrame f = new JFrame("Book List"); 
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                Connection con = Library.connect();
                String sql="SELECT * FROM BOOK WHERE BOOK_ID NOT IN (SELECT BOOK_ID FROM ISSUEDBOOKS) ORDER BY BOOK_NAME ASC";
                try {
                        Statement stmt = con.createStatement();
                        stmt.executeUpdate("USE LIBRARYMANAGEMENTSYSTEM");
                        ResultSet rs = stmt.executeQuery(sql);
                        JTable book_list= new JTable(Library.buildTableModel(rs)); 
                        JScrollPane scrollPane = new JScrollPane(book_list); 
                        f.add(scrollPane);
                        f.setSize(800, 400); 
                        f.setVisible(true);
                        f.setLocationRelativeTo(null);
                } catch (Exception e) {
                     e.printStackTrace();
                }  
        }//GEN-LAST:event_jButton10ActionPerformed

        private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
                // TODO add your handling code here:
                Library.admin = false;
                this.dispose();
                
        }//GEN-LAST:event_jButton11ActionPerformed

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                // TODO add your handling code here:
                
                Library.reset();
                JOptionPane.showMessageDialog(null, "Reset Done!");
                
        }//GEN-LAST:event_jButton5ActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                Library.admin = true;
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Register().setVisible(true);
                        }
                });
                
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                // TODO add your handling code here:
                Library.admin = false;
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Register().setVisible(true);
                        }
                });
        }//GEN-LAST:event_jButton4ActionPerformed

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                // TODO add your handling code here:
                JFrame f = new JFrame("Student List"); 
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                Connection con = Library.connect();
                String sql="SELECT STUDENT.STUDENT_ID, USER.USER_NAME, USER.USER_COLLEGE_ID, USER.USER_PHONE_NUMBER FROM USER INNER JOIN STUDENT ON USER.USER_ID = STUDENT.STUDENT_ID";
                try {
                        Statement stmt = con.createStatement();
                        stmt.executeUpdate("USE LIBRARYMANAGEMENTSYSTEM");
                        ResultSet rs = stmt.executeQuery(sql);
                        JTable book_list= new JTable(Library.buildTableModel(rs)); 
                        JScrollPane scrollPane = new JScrollPane(book_list); 
                        f.add(scrollPane);
                        f.setSize(800, 400); 
                        f.setVisible(true);
                        f.setLocationRelativeTo(null);
                } catch (Exception e) {
                     e.printStackTrace();
                }        
        }//GEN-LAST:event_jButton6ActionPerformed

        private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                
                JFrame f = new JFrame("Teacher List"); 
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                Connection con = Library.connect();
                String sql="SELECT TEACHER.TEACHER_ID, USER.USER_NAME, USER.USER_COLLEGE_ID, USER.USER_PHONE_NUMBER FROM USER INNER JOIN TEACHER ON USER.USER_ID = TEACHER.TEACHER_ID";
                try {
                        Statement stmt = con.createStatement();
                        stmt.executeUpdate("USE LIBRARYMANAGEMENTSYSTEM");
                        ResultSet rs = stmt.executeQuery(sql);
                        JTable book_list= new JTable(Library.buildTableModel(rs)); 
                        JScrollPane scrollPane = new JScrollPane(book_list); 
                        f.add(scrollPane);
                        f.setSize(800, 400); 
                        f.setVisible(true);
                        f.setLocationRelativeTo(null);
                } catch (Exception e) {
                     e.printStackTrace();
                }     
                
        }//GEN-LAST:event_jButton7ActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                // TODO add your handling code here:
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new BookDetails().setVisible(true);
                        }
                });
        }//GEN-LAST:event_jButton3ActionPerformed

        /**
         * @param args the command line arguments
         */

        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JButton jButton1;
        public javax.swing.JButton jButton10;
        public javax.swing.JButton jButton11;
        public javax.swing.JButton jButton2;
        public javax.swing.JButton jButton3;
        public javax.swing.JButton jButton4;
        public javax.swing.JButton jButton5;
        public javax.swing.JButton jButton6;
        public javax.swing.JButton jButton7;
        public javax.swing.JButton jButton8;
        public javax.swing.JButton jButton9;
        // End of variables declaration//GEN-END:variables
}
