/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;  
import java.time.Duration;
import java.util.Date;  
import java.util.concurrent.TimeUnit;

/**
 *
 * @author ashutosh
 */
public class IssueBook extends javax.swing.JFrame {

        /**
         * Creates new form IssueBook
         */
        public IssueBook() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                a = new javax.swing.JTextField();
                b = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                c = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                rr = new javax.swing.JTextField();
                jButton2 = new javax.swing.JButton();

                FormListener formListener = new FormListener();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setText("Book ID");

                jLabel2.setText("Student ID");

                jButton1.setText("ISSUE BOOK");
                jButton1.addActionListener(formListener);

                jLabel3.setText("Date (dd-mm-yy)");

                jLabel4.setText("Book ID");

                rr.addActionListener(formListener);

                jButton2.setText("RETURN");
                jButton2.addActionListener(formListener);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rr, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(a, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                                        .addComponent(b)
                                                        .addComponent(c))))
                                .addGap(108, 108, 108))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(rr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                );

                pack();
        }

        // Code for dispatching events from components to event handlers.

        private class FormListener implements java.awt.event.ActionListener {
                FormListener() {}
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                        if (evt.getSource() == jButton1) {
                                IssueBook.this.jButton1ActionPerformed(evt);
                        }
                        else if (evt.getSource() == rr) {
                                IssueBook.this.rrActionPerformed(evt);
                        }
                        else if (evt.getSource() == jButton2) {
                                IssueBook.this.jButton2ActionPerformed(evt);
                        }
                }
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                
                try {
                        if(a.getText().equals("") || b.getText().equals("") || c.getText().equals("")) {
                                JOptionPane.showMessageDialog(null, "Fill complete Details!");
                                return;
                        }
                        
                        Connection con = Library.connect();
                        Statement stmt = con.createStatement();
                        stmt.execute("USE LIBRARYMANAGEMENTSYSTEM");
                        Date date = new Date();
                        
                        SimpleDateFormat f = new SimpleDateFormat("dd-MM-yy");
                        
                        String iid = f.format(date);
                        
                        String query = "INSERT INTO " + "ISSUEDBOOKS" + " VALUES ('"  + iid + "', '" +
                        
                        a.getText() + "', '" + b.getText() +  "', '" + Library.user + "','" + c.getText() + "'," + "'N/A'," + "0" + ")";
                        
                        stmt.executeUpdate(query);
                        JOptionPane.showMessageDialog(null, "Book Issued successfully!!");
                        
                }
                catch (Exception e) {
                        e.printStackTrace();
                }
        }//GEN-LAST:event_jButton1ActionPerformed

        private void rrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rrActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_rrActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
                try {
                        if(rr.getText().equals("")) {
                                JOptionPane.showMessageDialog(null, "Fill complete Details!");
                                return;
                        }
                        
                        Connection con = Library.connect();
                        Statement stmt = con.createStatement();
                        stmt.execute("USE LIBRARYMANAGEMENTSYSTEM");
                        Date date1 = new Date();
                        
                        SimpleDateFormat f = new SimpleDateFormat("dd-MM-yy");
                        
                        String iid = f.format(date1);
                        
                        Date date2 = new Date();
                        
                        
                        String query = "SELECT * FROM ISSUEDBOOKS WHERE BOOK_ID = '" + rr.getText() + "' AND RETURN_DATE = 'N/A'" ;
                        ResultSet rs = stmt.executeQuery(query);
                        if(!rs.next()) {
                             JOptionPane.showMessageDialog(null, "Invalid Book ID!!");
                             return;
                        }
                        date2 = f.parse(rs.getString("ISSUE_DATE"));
                        long diff = date2.getTime() - date1.getTime();
                        long days = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
                        int fine = (int) (Math.max(0, days - 15) * 2);
                        JOptionPane.showMessageDialog(null, "Total Fine: " + Integer.toString(fine));
                        query = "UPDATE ISSUEDBOOKS " + "SET RETURN_DATE = '" + f.format(date1) + "', FINE_PAID = " + Integer.toString(fine) + " WHERE BOOK_ID = '" + rr.getText() + "' AND RETURN_DATE = 'N/A'" ;
//                        System.out.print(query);
                        stmt.executeUpdate(query);
                        JOptionPane.showMessageDialog(null, "Book Returned!");
                        
                        
                }
                catch (Exception e) {
                        e.printStackTrace();
                }
        }//GEN-LAST:event_jButton2ActionPerformed

        /**
         * @param args the command line arguments
         */
//        public static void main(String args[]) {
//                /* Set the Nimbus look and feel */
//                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//                 */
//                try {
//                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                                if ("Nimbus".equals(info.getName())) {
//                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                                        break;
//                                }
//                        }
//                } catch (ClassNotFoundException ex) {
//                        java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//                } catch (InstantiationException ex) {
//                        java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//                } catch (IllegalAccessException ex) {
//                        java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//                        java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//                }
//                //</editor-fold>
//
//                /* Create and display the form */
//                java.awt.EventQueue.invokeLater(new Runnable() {
//                        public void run() {
//                                new IssueBook().setVisible(true);
//                        }
//                });
//        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JTextField a;
        public javax.swing.JTextField b;
        public javax.swing.JTextField c;
        public javax.swing.JButton jButton1;
        public javax.swing.JButton jButton2;
        public javax.swing.JLabel jLabel1;
        public javax.swing.JLabel jLabel2;
        public javax.swing.JLabel jLabel3;
        public javax.swing.JLabel jLabel4;
        public javax.swing.JTextField rr;
        // End of variables declaration//GEN-END:variables
}
