DROP DATABASE LIBRARYMANAGEMENTSYSTEM;
CREATE DATABASE LIBRARYMANAGEMENTSYSTEM;
USE LIBRARYMANAGEMENTSYSTEM;

CREATE TABLE BOOK (
	BOOK_ID	VARCHAR(20)	NOT NULL,
	BOOK_NAME VARCHAR(20) NOT NULL,
	BOOK_AUTHOR VARCHAR(20) NOT NULL,
	BOOK_PUBLISHER VARCHAR(20) NOT NULL,
        BOOK_SHELF VARCHAR(20) NOT NULL,
	PRIMARY KEY(BOOK_ID)
);


CREATE TABLE USER (
	USER_ID VARCHAR(20) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL,
	USER_PASSWORD VARCHAR(20) NOT NULL,
	USER_COLLEGE_ID VARCHAR(20),
	USER_PHONE_NUMBER BIGINT NOT NULL,
	PRIMARY KEY(USER_ID)
);


CREATE TABLE TEACHER(
	TEACHER_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY(TEACHER_ID),
	FOREIGN KEY(TEACHER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE STUDENT(
	STUDENT_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY(STUDENT_ID),
	FOREIGN KEY(STUDENT_ID) REFERENCES USER(USER_ID)
);


CREATE TABLE ISSUEDBOOKS(
	ISSUE_ID VARCHAR(20) NOT NULL,
	BOOK_ID VARCHAR(20) NOT NULL,
	STUDENT_ID VARCHAR(20) NOT NULL,
	ISSUER_ID VARCHAR(20) NOT NULL,
	ISSUE_DATE VARCHAR(20) NOT NULL,
	RETURN_DATE VARCHAR(20),
	FINE_PAID INT,
	PRIMARY KEY(ISSUE_ID),
	FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
	FOREIGN KEY(ISSUER_ID) REFERENCES TEACHER(TEACHER_ID),
	FOREIGN KEY(BOOK_ID) REFERENCES BOOK(BOOK_ID)
);


USE LIBRARYMANAGEMENTSYSTEM;
SELECT STUDENT.STUDENT_ID, USER.USER_NAME, USER.USER_COLLEGE_ID, USER.USER_PHONE_NUMBER FROM USER INNER JOIN STUDENT ON USER.USER_ID = STUDENT.STUDENT_ID;
SELECT TEACHER.TEACHER_ID, USER.USER_NAME, USER.USER_COLLEGE_ID, USER.USER_PHONE_NUMBER FROM USER INNER JOIN TEACHER ON USER.USER_ID = TEACHER.TEACHER_ID;

UPDATE ISSUEDBOOKS SET FINE_PAID = 1 WHERE BOOK_ID = 'bk' AND RETURN_DATE = 'N/A';

SELECT BOOK.BOOK_NAME, BOOK.BOOK_ID, BOOK.BOOK_NAME, BOOK.BOOK_AUTHOR, BOOK.BOOK_PUBLISHER, BOOK.BOOK_SHELF, ISSUEDBOOKS.STUDENT_ID FROM BOOK INNER JOIN ISSUEDBOOKS ON BOOK.BOOK_ID = ISSUEDBOOKS.BOOK_ID;

SELECT * FROM ISSUEDBOOKS WHERE BOOK_ID = 'bk' AND RETURN_DATE = 'N/A';