/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author ashutosh
 */
public class TeacherMenu extends javax.swing.JFrame {

        /**
         * Creates new form TeacherMenu
         */
        public TeacherMenu() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();

                FormListener formListener = new FormListener();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jButton1.setText("Issue or Return Book");
                jButton1.addActionListener(formListener);

                jButton2.setText("View Books Issued By You");
                jButton2.addActionListener(formListener);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(220, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(111, Short.MAX_VALUE))
                );

                pack();
        }

        // Code for dispatching events from components to event handlers.

        private class FormListener implements java.awt.event.ActionListener {
                FormListener() {}
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                        if (evt.getSource() == jButton1) {
                                TeacherMenu.this.jButton1ActionPerformed(evt);
                        }
                        else if (evt.getSource() == jButton2) {
                                TeacherMenu.this.jButton2ActionPerformed(evt);
                        }
                }
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new IssueBook().setVisible(true);
                        }
                });
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
                JFrame f = new JFrame("Book List"); 
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                Connection con = Library.connect();
                String sql= "SELECT BOOK.BOOK_NAME, BOOK.BOOK_ID, BOOK.BOOK_AUTHOR, BOOK.BOOK_PUBLISHER, BOOK.BOOK_SHELF, ISSUEDBOOKS.STUDENT_ID FROM BOOK INNER JOIN " +
                        "ISSUEDBOOKS ON BOOK.BOOK_ID = ISSUEDBOOKS.BOOK_ID " +
                        "WHERE ISSUEDBOOKS.ISSUER_ID = '" + Library.user + "'" ;
                try {
                        Statement stmt = con.createStatement();
                        stmt.executeUpdate("USE LIBRARYMANAGEMENTSYSTEM");
                        ResultSet rs = stmt.executeQuery(sql);
                        JTable book_list= new JTable(Library.buildTableModel(rs)); 
                        JScrollPane scrollPane = new JScrollPane(book_list); 
                        f.add(scrollPane);
                        f.setSize(800, 400); 
                        f.setVisible(true);
                        f.setLocationRelativeTo(null);
                } catch (Exception e) {
                     e.printStackTrace();
                }  
        }//GEN-LAST:event_jButton2ActionPerformed

        /**
         * @param args the command line arguments
         */
//        public static void main(String args[]) {
//                /* Set the Nimbus look and feel */
//                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//                 */
//                try {
//                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                                if ("Nimbus".equals(info.getName())) {
//                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                                        break;
//                                }
//                        }
//                } catch (ClassNotFoundException ex) {
//                        java.util.logging.Logger.getLogger(TeacherMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//                } catch (InstantiationException ex) {
//                        java.util.logging.Logger.getLogger(TeacherMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//                } catch (IllegalAccessException ex) {
//                        java.util.logging.Logger.getLogger(TeacherMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//                        java.util.logging.Logger.getLogger(TeacherMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//                }
//                //</editor-fold>
//
//                /* Create and display the form */
//                java.awt.EventQueue.invokeLater(new Runnable() {
//                        public void run() {
//                                new TeacherMenu().setVisible(true);
//                        }
//                });
//        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JButton jButton1;
        public javax.swing.JButton jButton2;
        // End of variables declaration//GEN-END:variables
}
